# SPDX-FileCopyrightText: 2023 Jose D. Montoya
#
# SPDX-License-Identifier: Unlicense

repos:
  - repo: https://github.com/python/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/pylint
    rev: v2.17.4
    hooks:
      - id: pylint
        name: pylint (library code)
        types: [python]
        args:
          - --disable=consider-using-f-string
        exclude: "^(docs/|examples/|tests/)"
      - id: pylint
        name: pylint (example code)
        description: Run pylint rules on "examples/*.py" files
        types: [python]
        files: "^examples/"
        args:
          - --disable=missing-docstring,invalid-name,consider-using-f-string,duplicate-code
