# SPDX-FileCopyrightText: 2023 Jose D. Montoya
#
# SPDX-License-Identifier: Unlicense

name: Build CI

on:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - uses: actions/checkout@v3

      - name: Build wheel
        run: pip wheel -w dist --no-deps .

      - name: check dist
        run: pipx run twine check dist/*

      - name: Archive wheel
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: ${{ github.workspace }}/dist/

  linters:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - uses: actions/checkout@v3

      - name: Install pre-commit and deps
        run: pip install pre-commit -r requirements.txt

      - name: Setup problem matchers
        uses: adafruit/circuitpython-action-library-ci-problem-matchers@v1

      - name: Pre-commit hooks
        run: pre-commit run --all-files

  build-bundles:
    runs-on: ubuntu-latest
    steps:
      - name: Translate Repo Name For Build Tools filename_prefix
        id: repo-name
        run: |
          echo repo-name=$(
          echo ${{ github.repository }} |
          awk -F '\/' '{ print tolower($2) }' |
          tr '_' '-'
          ) >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: adafruit/actions-ci-circuitpython-libs
          path: actions-ci

      - name: Install deps
        run: |
          source actions-ci/install.sh

      - name: Build assets
        run: circuitpython-build-bundles --filename_prefix ${{ steps.repo-name.outputs.repo-name }} --library_location .

      - name: Archive bundles
        uses: actions/upload-artifact@v3
        with:
          name: bundles
          path: ${{ github.workspace }}/bundles/

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          pip install -r docs/requirements.txt -r requirements.txt

      - name: Build docs
        working-directory: docs
        run: sphinx-build -E -W -b html . _build/html

      - name: Archive docs
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ${{ github.workspace }}/docs/_build/html
