# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: GitHub Release Actions

on:
  release:
    types: [published]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
    - name: Run GitHub Release CI workflow
      uses: tekktrik/workflows-circuitpython-libs/release-gh@test/mpy-bundle
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        upload-url: ${{ github.event.release.upload_url }}
        package-prefix: circuitpython_uplot
